# Generated by Django 5.2.13 on 2026-04-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Movies', 'Movies'), ('Comedy', 'Comedy'), ('Concerts', 'Concerts'), ('Sports', 'Sports'), ('Theatre', 'Theatre')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('certificate', models.CharField(blank=True, max_length=10)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
