"""
Django settings for smartbook project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
BASE_DIR = Path(__file__).resolve().parent.parent
# ─────────────────────────────────────────────
# JAZZMIN SETTINGS — SmartBook Admin Theme
# ─────────────────────────────────────────────
JAZZMIN_SETTINGS = {
    "custom_css": "admin/css/custom_admin.css",
    # ── Branding ──────────────────────────────
    "site_title": "SmartBook Admin",
    "site_header": "SmartBook",
    "site_brand": "🎟 SmartBook",
    "welcome_sign": "Welcome to SmartBook Admin Panel",
    "copyright": "SmartBook © 2025",

    # ── Top Search Bar ─────────────────────────
    "search_model": ["auth.user", "events.event", "bookings.booking"],

    # ── User Avatar ────────────────────────────
    "user_avatar": None,

    # ── Top Navigation (navbar) ────────────────
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "View Site", "url": "/", "new_window": True},
        {"model": "auth.user"},
    ],

    # ── Side Navigation Icons ──────────────────
    "icons": {
    "auth":                     "fas fa-users-cog",
    "auth.user":                "fas fa-user",
    "auth.Group":               "fas fa-users",
    "users.userprofile":        "fas fa-id-card",
    "users.otp":                "fas fa-key",
    "events.event":             "fas fa-film",
    "venues.venue":             "fas fa-map-marker-alt",
    "venues.show":              "fas fa-clapperboard",
    "bookings.booking":         "fas fa-ticket-alt",
    "bookings.seatlock":        "fas fa-lock",
},
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",

    # ── UI Options ─────────────────────────────
    "related_modal_active": True,
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],

    # ── Order of Apps in Sidebar ───────────────
    "order_with_respect_to": [
        "auth",
        "users",
        "events",
        "bookings",
        "venues",
    ],

    # ── Custom Links in Sidebar ────────────────
    "custom_links": {
    "bookings": [{
        "name": "All Bookings",
        "url": "admin:bookings_booking_changelist",
        "icon": "fas fa-list",
        "permissions": ["bookings.view_booking"],
    }],
},

    # ── Language / i18n ────────────────────────
    "language_chooser": False,
}

# ─────────────────────────────────────────────
# JAZZMIN UI TWEAKS — Dark Purple SmartBook Theme
# ─────────────────────────────────────────────
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,

    # ── Core Theme ─────────────────────────────
    "theme": "darkly",          # Dark base theme
    "dark_mode_theme": "darkly",

    # ── Navbar ─────────────────────────────────
    "navbar": "navbar-dark",
    "no_navbar_border": True,
    "navbar_fixed": True,

    # ── Sidebar ────────────────────────────────
    "sidebar": "sidebar-dark-purple",
    "sidebar_fixed": True,
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,

    # ── Brand / Accent ─────────────────────────
    "brand_colour": "navbar-purple",
    "accent": "accent-purple",

    # ── Buttons ────────────────────────────────
    "button_classes": {
        "primary":   "btn-primary",
        "secondary": "btn-secondary",
        "info":      "btn-info",
        "warning":   "btn-warning",
        "danger":    "btn-danger",
        "success":   "btn-success",
    },

    # ── Actions ────────────────────────────────
    "actions_sticky_top": True,
}

# Build paths inside the project like this: BASE_DIR / 'subdir'.



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w@6!x3rkl!fr(wp6szwk=u4*_t($+ii(!)phed0m2a499r1jro'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',  # ← ADD THIS AS THE VERY FIRST LINE
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party
    'rest_framework',
    'corsheaders',
    'rest_framework.authtoken',
    # Our apps
    'users',
    'events',
    'bookings',
    'venues',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'smartbook.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'smartbook.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'smartbook',
        'USER': 'postgres',
        'PASSWORD': 'admin123',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'smartbook' / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# CORS Settings
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
]

# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
}

# Media files (movie posters, images)
import os
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Razorpay Keys (Test Mode)
RAZORPAY_KEY_ID = 'rzp_test_your_key_here'
RAZORPAY_KEY_SECRET = 'your_secret_here'