# Generated by Django 5.2.13 on 2026-04-26 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('total_seats', models.IntegerField(default=200)),
                ('amenities', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_date', models.DateField()),
                ('show_time', models.TimeField()),
                ('screen', models.CharField(blank=True, max_length=50)),
                ('total_seats', models.IntegerField(default=200)),
                ('available_seats', models.IntegerField(default=200)),
                ('price_premium', models.DecimalField(decimal_places=2, default=350, max_digits=8)),
                ('price_gold', models.DecimalField(decimal_places=2, default=250, max_digits=8)),
                ('price_silver', models.DecimalField(decimal_places=2, default=180, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.venue')),
            ],
        ),
    ]
